site_name: BRNS
site_description: "Biogeochemical Reaction Network Simulator"

theme:
    name: "material"
    palette:
        primary: "cyan"
        accent: "grey"

plugins:
    - search
    - mkdocstrings:
        default_handler: python
    - mkdocs-jupyter:
        execute: true

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
    - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
    - javascripts/katex.js

extra_css:
    - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css

nav:
    - "Start": README.md
    - "Transport model": model.md
    - "Reaction network example": reaction_term_rk_yaml.md
    - "Literature": references.md
    - "Linux / WSL installation": linux_installation.md
    - "Windows installation": windows_installation.md
    - "YAML Model Reference": yaml_model_reference.md
    - "Developer pipeline": developer_pipeline.md
    - "acg": api_acg.md
    - "gaussian_elimination": api_gaussian_elimination.md
    - "acg_orchestrator": api_acg_orchestrator.md