site_name: BRNS
site_description: "Biogeochemical Reaction Network Simulator"
site_url: "https://jtecklenburg.github.io/BRNS/"
repo_url: "https://github.com/jtecklenburg/BRNS"
repo_name: "jtecklenburg/BRNS"

theme:
  name: material
  palette:
    primary: teal
    accent: blue grey
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Start: index.md
  - API:
      - acg: api_acg.md
      - gaussian_elimination: api_gaussian_elimination.md
      - acg_orchestrator: api_acg_orchestrator.md
